list = ['a', 100, 'abc', 100.10, True]
list.append('Ram')
print(list)
print(list.count(100))
print(list.index('abc'))
list.insert(2, 'Hello')
print(list)
list.remove('abc')
print(list)
list.reverse()
print(list)
list.sort(key=str)
print(list)
print(len(list))